name: Gitub Actions Secret Example

on:
  push:
    branches: [ main ]
    
jobs:
  secrets-in-github-actions:
    runs-on: windows-latest
    
    # The Secret Actions Github example has three steps
    steps:
      # Show how to print unmasked Github secrets to the console
      - name: Step 1 - Echo out a Github Actions Secret to the logs
        run: |
          echo "The Github Action Secret will be masked: "
          echo ${{ secrets.SECRET_TOKEN }}
          echo "Trick to echo Github ACtions Secret: "
          echo ${{secrets.SECRET_TOKEN}} | sed 's/./& /g'
          
      # Use a Github Actions secret variable in a bash shell
      - name: Step 2 - Github Action if statement (true)
        env:
          PARADISE_SECRET: ${{ secrets.SECRET_TOKEN }}
        if: env.PARADISE_SECRET == 'Patience!!'
        run: echo "I konw the secret to Paradise is!"
        
             
      # Use a Github Actions secret variable in a bash shell
      - name: Step 3 - Github Action if statement (false)
        shell: bash
        env:
          PARADISE_SECRET: ${{ secrets.SECRET_TOKEN }}
        if: env.PARADISE_SECRET != 'Impatience!!'
        run: echo "I can never Know the secret to Paradise!"
        
        
          
          
